export const Users = [
    {
      id:1,
      profilePicture: "assets/person/p1.jpg",
      username: "Aatif ansari",
    },
    {
      id:2,
      profilePicture: "assets/person/p2.jpg",
      username: "Pooja",
    },
    {
      id:3,
      profilePicture: "assets/person/p3.jpg",
      username: "Alex",
    },
    {
      id:4,
      profilePicture: "assets/person/p4.jpg",
      username: "Dora Hawks",
    },
    {
      id:5,
      profilePicture: "assets/person/p5.jpg",
      username: "Thomas ",
    },
    {
      id:6,
      profilePicture: "assets/person/p6.jpg",
      username: "Simaran",
    },
    {
      id:7,
      profilePicture: "assets/person/p7.jpg",
      username: "Yash",
    },
    {
      id:8,
      profilePicture: "assets/person/p2.jpg",
      username: "Happy",
    },
    {
      id:9,
      profilePicture: "assets/person/p2.jpg",
      username: "Sanjay",
    },
    {
      id:10,
      profilePicture: "assets/person/p2.jpg",
      username: "Suraj singh",
    },
  ];
  
  export const Posts = [
    {
      id: 1,
      desc: "Love For All, Hatred For None.",
      photo: "assets/post/1post.jpg",
      date: "5 mins ago",
      userId: 1,
      like: 32,
      comment: 9,
    },
    {
      id: 2,
      photo: "assets/post/2post.jpg",
      date: "15 mins ago",
      userId: 2,
      like: 2,
      comment: 1,
    },
    {
      id: 3,
      desc: "Every moment is a fresh beginning.",
      photo: "assets/post/3p.jpg",
      date: "1 hour ago",
      userId: 3,
      like: 61,
      comment: 2,
    },
    {
      id: 4,
      photo: "assets/post/4post.jpg",
      date: "4 hours ago",
      userId: 4,
      like: 7,
      comment: 3,
    },
    {
      id: 5,
      photo: "assets/post/5post.jpg",
      date: "5 hours ago",
      userId: 5,
      like: 23,
      comment: 5,
    },
    {
      id: 6,
      photo: "assets/post/6post.jpg",
      date: "1 day ago",
      userId: 6,
      like: 44,
      comment: 6,
    },
    {
      id: 7,
      desc: "Never regret anything that made you smile.",
      photo: "assets/post/1post.jpg",
      date: "2 days ago",
      userId: 7,
      like: 52,
      comment: 3,
    },
    {
      id: 8,
      photo: "assets/post/2post.jpg",
      date: "3 days ago",
      userId: 8,
      like: 15,
      comment: 1,
    },
    {
      id: 9,
      desc: "Change the world by being yourself.",
      photo: "assets/post/3p.jpg",
      date: "5 days ago",
      userId: 9,
      like: 11,
      comment: 2,
    },
    {
      id: 10,
      photo: "assets/post/4post.jpg",
      date: "1 week ago",
      userId: 10,
      like: 104,
      comment: 12,
    },
  ];